### ISSUE TITLE
Create Buttons design system

### ISSUE THREAD

**Issue by n1c01a5** [GoodHive/app#4]

**Comment by alfonsom-cogent** [comment]
$PR #15

**Comment by alfonsom-cogent** [comment]
$PR #16 completed button component

**Comment by n1c01a5** [comment]
$PR https://github.com/GoodHive/app/pull/16

**Comment by n1c01a5** [comment]
@alfonsom-cogent there is no deal for this issue that's why you cannot claim any reward.
