### ISSUE TITLE
Create Talent Card design system

### ISSUE THREAD

**Issue by n1c01a5** [GoodHive/app#6]
See https://www.figma.com/file/pfqWpXzacijRjsIlG4TXPt/GoodHive---20OCT2022%2C-Ver01?node-id=152%3A6906&t=LgGTvxs4GtQynmAe-4 .

**Comment by alfonsom-cogent** [comment]
$PR #18

**Comment by n1c01a5** [comment]
Change the Apply button to "Know more" and "Contact" (Telegram Link).

See https://www.figma.com/file/HXZNIK88stgIazQc19QSkq/GoodHive---Final-Draft?node-id=0-1&t=TTEQYpNlWItiGOmD-0 .
