### ISSUE TITLE
Create Navbar design system

### ISSUE THREAD

**Issue by n1c01a5** [GoodHive/app#7]
Follow this navbar : [Figma](https://www.figma.com/file/0y5MvIJUj42FZy6Z7d27DN/GoodHive---20OCT2022%2C-Ver01-(Copy)?node-id=526%3A3814&t=pGLOAoL0RgSkcWQJ-4).

Note: The navbar is working in progress but not finished.

**Comment by alfonsom-cogent** [comment]
$PR #12

**Comment by n1c01a5** [comment]
$PR https://github.com/GoodHive/app/pull/12

**Comment by alfonsom-cogent** [comment]
I has some troubles with husky in the last branch. so I have created a new branch $PR #14

**Comment by alfonsom-cogent** [comment]
$PR #16 completed Navbar component

**Comment by n1c01a5** [comment]
The navbar is conditionnal about the context.

There are 3 contexts :
- common
- freelancer
- client
