### ISSUE TITLE
Add employment type in job offer

### ISSUE THREAD

**Issue by LittleSweetGun** [GoodHive/app#71]
Update job_offer table

CREATE TABLE goodhive.job_offers (
id SERIAL PRIMARY KEY,
title VARCHAR(100) NOT NULL,
type_engagement VARCHAR(100) NOT NULL,
description VARCHAR(255) NOT NULL,
duration VARCHAR(100) NOT NULL,
rate_per_hour VARCHAR(100) NOT NULL,
budget VARCHAR(100) NOT NULL,
skills VARCHAR(255) NOT NULL,
type_employment VARCHAR(100)
);

Add input space for employment type in create-job page

**Comment by n1c01a5** [comment]
@LittleSweetGun can we close this issue ?
